# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2025-08-28 05:46:10
"""
import arcpy
from sys import argv

#For inline variable substitution, parameters passed as a String are evaluated using locals(), globals() and isinstance(). To override, substitute values directly.
def SummarizeInvasiveSpecies(Human_Contact_Locations, Buffer_Distance, Invasive_species, Area_Unit_of_Measure, Output_Feature_Class):  # Summerize invasive species

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    arcpy.ImportToolbox(r"c:\program files\arcgis\pro\Resources\ArcToolbox\toolboxes\Analysis Tools.tbx")

    # Process: Pairwise Buffer (Pairwise Buffer) (analysis)
    Contact_Location_Buffers = "C:\\Users\\debna\\OneDrive\\Documents\\ArcGIS\\Packages\\Make a geoprocessing model_d57e3d\\commondata\\make_a_geoprocessing_model.gdb\\CommercialCamp_PairwiseBuffe"
    arcpy.analysis.PairwiseBuffer(in_features=Human_Contact_Locations.__str__().format(**locals(),**globals())if isinstance(Human_Contact_Locations, str) else Human_Contact_Locations, out_feature_class=Contact_Location_Buffers, buffer_distance_or_field=Buffer_Distance.__str__().format(**locals(),**globals())if isinstance(Buffer_Distance, str) else Buffer_Distance)

    # Process: Summarize Within (Summarize Within) (analysis)
    Output_Grouped_Table = ""
    arcpy.analysis.SummarizeWithin(in_polygons=Contact_Location_Buffers, in_sum_features=Invasive_species.__str__().format(**locals(),**globals())if isinstance(Invasive_species, str) else Invasive_species, out_feature_class=Output_Feature_Class.__str__().format(**locals(),**globals())if isinstance(Output_Feature_Class, str) else Output_Feature_Class, shape_unit=Area_Unit_of_Measure.__str__().format(**locals(),**globals())if isinstance(Area_Unit_of_Measure, str) else Area_Unit_of_Measure, out_group_table=Output_Grouped_Table)

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace="C:\\Users\\debna\\OneDrive\\Documents\\ArcGIS\\Packages\\Make a geoprocessing model_d57e3d\\commondata\\make_a_geoprocessing_model.gdb", workspace="C:\\Users\\debna\\OneDrive\\Documents\\ArcGIS\\Packages\\Make a geoprocessing model_d57e3d\\commondata\\make_a_geoprocessing_model.gdb"):
        SummarizeInvasiveSpecies(*argv[1:])
